apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topic
  namespace: kafka
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-topic
          image: bitnami/kafka:3.6.0
          command:
            - bash
            - -c
            - |
              kafka-topics.sh --create --topic website-events --bootstrap-server kafka.kafka.svc.cluster.local:9092 --partitions 1 --replication-factor 1 || true
