apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-azure-dns
spec:
  acme:
    email: admin@{{BASE_DOMAIN}}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-azure-dns
    solvers:
      - dns01:
          azureDNS:
            clientID: "{{AZURE_CLIENT_ID}}"
            tenantID: "{{AZURE_TENANT_ID}}"
            subscriptionID: "{{AZURE_SUBSCRIPTION_ID}}"
            resourceGroupName: "{{AZURE_DNS_RESOURCE_GROUP}}"
            hostedZoneName: "{{AZURE_DNS_ZONE}}"
