apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-{{NAMESPACE}}
  namespace: {{NAMESPACE}}
spec:
  hard:
    requests.cpu: "2"
    limits.cpu: "4"
    requests.memory: 4Gi
    limits.memory: 8Gi
    pods: "20"
    persistentvolumeclaims: "2"
